model_name: &MODEL_NAME MyNet
dataset_name: &DATASET_NAME minist

# experiment name or current model name
exper: &EXPER 'base'

dataset:
    name: *DATASET_NAME
    root: data
    mode: train
    download: true
    loader:
        batch_size: &TRAIN_BATCH 200
        shuffle: true
        num_workers: &TRAIN_NUM_WORKERS 0

model:
    name: *MODEL_NAME
    optim: &OPTIM 
        name: Adam
        lr: 1.0e-3
        weight_decay: 0.01
    sched:
        name: StepLR
        step_size: 4
        gamma: 0.5

train:
    model:
    trainer:
        max_epochs: 10
        precision: 32
        devices: [0]
        accelerator: gpu
        strategy: ddp # ddp_find_unused_parameters_false
        sync_batchnorm: false
        reload_dataloaders_every_n_epochs: 10
        log_every_n_steps: 15
        callbacks:
            TxtLogger:
                name: *MODEL_NAME
                batch_size: *TRAIN_BATCH
            CKPTFormatter:
    trainset:
        loader:
            batch_size: *TRAIN_BATCH
            shuffle: true
            num_workers: *TRAIN_NUM_WORKERS
    valset:
        mode: val
        loader:
            batch_size: *TRAIN_BATCH
            shuffle: false
            num_workers: *TRAIN_NUM_WORKERS
    ckpt_path: 

test:
    model:
    ckpt_path: checkpoints/base/version_0/checkpoints/e4-s1500-loss9.9744.ckpt
    dataset:
        mode: val
        loader:
            batch_size: &VAL_BATCH 1
            shuffle: false
            num_workers: 0
    trainer:
        max_epochs: 1
        devices: [0]
        accelerator: gpu
        callbacks:
            TxtLogger:
                name: *MODEL_NAME
                batch_size: *VAL_BATCH

