MODEL_NAME: &MODEL_NAME MyNet
DATASET_NAME: &DATASET_NAME minist

# experiment name or current model name
EXPER: &EXPER 'base'

DATASET:
    NAME: *DATASET_NAME
    ROOT: data
    MODE: train
    DOWNLOAD: true
    LOADER:
        BATCH_SIZE: &TRAIN_BATCH 200
        SHUFFLE: true
        NUM_WORKERS: &TRAIN_NUM_WORKERS 0

MODEL:
    NAME: *MODEL_NAME
    OPTIM: &OPTIM adam
    SCHED: steplr

TRAIN:
    MODEL:
        LEARNING_RATE: &LR 1.0e-4
    TRAINER:
        MAX_EPOCHS: 10
        PRECISION: 32
        DEVICES: [0]
        ACCELERATOR: gpu
        STRATEGY: ddp # ddp_find_unused_parameters_false
        SYNC_BATCHNORM: false
        RELOAD_DATALOADERS_EVERY_N_EPOCHS: 10
        LOG_EVERY_N_STEPS: 15
        CALLBACKS:
            TxtLoggerCallback:
                NAME: *MODEL_NAME
                BATCH_SIZE: *TRAIN_BATCH
            CKPTCallback:
    TRAINSET:
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: true
            NUM_WORKERS: *TRAIN_NUM_WORKERS
    VALSET:
        MODE: val
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: false
            NUM_WORKERS: *TRAIN_NUM_WORKERS
    CKPT_PATH: checkpoints/base/version_0/checkpoints/e4-s1500-loss9.9744.ckpt

TEST:
    MODEL:
        LEARNING_RATE: *LR
    CKPT_PATH: checkpoints/base/version_0/checkpoints/e4-s1500-loss9.9744.ckpt
    DATASET:
        MODE: val
        LOADER:
            BATCH_SIZE: &VAL_BATCH 1
            SHUFFLE: false
            NUM_WORKERS: 0
    TRAINER:
        MAX_EPOCHS: 1
        DEVICES: [0]
        ACCELERATOR: gpu
        CALLBACKS:
            TxtLoggerCallback:
                NAME: *MODEL_NAME
                BATCH_SIZE: *VAL_BATCH

